export default {
  // navTheme: 'dark',
  // primaryColor: '#1890FF',
  // layout: 'sidemenu',
  // contentWidth: 'Fluid',
  // fixedHeader: false,
  // autoHideHeader: false,
  // fixSiderbar: false,
  // colorWeak: false,
  // menu: {
  //   locale: true,
  // },
  // title: 'Ant Design Pro',
  // pwa: false,
  // iconfontUrl: '',

  navTheme: 'light',
  primaryColor: '#40a9ff',
  layout: 'sidemenu',
  contentWidth: 'Fluid',
  fixedHeader: false,
  autoHideHeader: false,
  fixSiderbar: false,
  menu: {
    locale: true,
  },
  title: '挂车管家',
  pwa: false,
  iconfontUrl: '',
  collapse: true,
  language: 'zh-CN',
};
